packages:
  - apps/*
  - packages/*
  - examples/*
  - integrations/*

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild

onlyBuiltDependencies:
  - better-sqlite3
  - sqlite3

overrides:
  punycode: ^2.3.1
