packages:
  - apps/*
  - packages/*
  - examples/*
  - integrations/*

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@auto-engineer/design-system-importer': link:../../../Library/pnpm/global/5/node_modules/@auto-engineer/design-system-importer
  punycode: ^2.3.1
