packages:
  - apps/*
  - packages/*
  - examples/*
  - integrations/*
  - '!examples/shopping-assistant'

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  punycode: ^2.3.1
