packages:
  - apps/*
  - packages/*
  - examples/*
  - integrations/*
  - '!examples/shopping-assistant'

ignoredBuiltDependencies:
  - '@apollo/protobufjs'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@auto-engineer/ai-gateway': link:packages/ai-gateway
  '@auto-engineer/flowlang': link:packages/flowlang
  punycode: ^2.3.1
